#!/usr/bin/env python3
"""Generate scripts/build-evidence-en.py from build-evidence.py.

The English article was shipping the Russian evidence gallery screenshots. This derives an
English builder from the Russian one by replacing only the chrome strings, so both galleries
keep reading the same saved JSON and can never drift apart in their numbers.

Data strings stay in their original language on purpose: the ticket state and the Score legend
are what was actually sent to the API in the first call, and the article says so.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "build-evidence.py"
DST = ROOT / "build-evidence-en.py"

# Each pair must match exactly once in the source, or the build fails loudly.
PAIRS = [
    # module docstring
    ('"""Build the article\'s evidence views from saved JSON and command logs; no API calls."""',
     '"""English evidence views. Generated by make-evidence-en.py; edit that, not this file."""'),
    # chrome
    ("Источники: %s", "Sources: %s"),
    ("Позиция на заданной шкале, а не вероятность.", "A position on the given scale, not a probability."),
    ("P(да): клиент нашёл обходной путь", "P(yes): the customer found a workaround"),
    ('probability_bar("да", noul["noul"])', 'probability_bar("yes", noul["noul"])'),
    ("У Noul нет отдельного confidence.", "Noul has no separate confidence."),
    ("<small>Состояние, переданное Jev</small>%s</div>",
     "<small>State sent to Jev</small>%s<em>The original request was written in Russian.</em></div>"),
    # these two are separate adjacent literals on separate source lines
    ("<span>API-запросов: <b>%s</b></span><span>Токены: <b>%s input / %s output</b></span>",
     "<span>API requests: <b>%s</b></span><span>Tokens: <b>%s input / %s output</b></span>"),
    ("<span>Сеть + API: <b>%s ms</b></span>", "<span>Network + API: <b>%s ms</b></span>"),
    ('"01 / Прямой вызов API", "Три решения из одного обращения"',
     '"01 / A direct API call", "Three decisions from one message"'),
    ("Реальный ответ <strong>%s</strong>; значения прочитаны из сохранённого JSON.",
     "A real <strong>%s</strong> answer. The values are read from the saved JSON."),
    ('"русский запрос"', '"Russian request"'),
    ('"ответ API"', '"API response"'),
    ('"метаданные запуска"', '"run metadata"'),
    ('("Категория обращения", "Choice · category")', '("Message category", "Choice · category")'),
    ('("Есть проверенный обходной путь?", "Noul · has_workaround")',
     '("Is there a verified workaround?", "Noul · has_workaround")'),
    ('("Следующая диагностика", "Choice · next_check")', '("Next diagnostic", "Choice · next_check")'),
    ('"Основной набор"', '"Primary set"'),
    ('"Независимый stress-набор"', '"Independent stress set"'),
    ("%s случаев · %s API-запросов", "%s cases · %s API requests"),
    ("<span>верных ответов</span>", "<span>correct answers</span>"),
    ("Принято политикой: %s; abstentions: %s; пропущено: %s.",
     "Accepted by policy: %s; abstentions: %s; unanswered: %s."),
    ('"02 / Две отдельные проверки", "Как Jev ответил на размеченные случаи"',
     '"02 / Two separate evaluations", "How Jev answered the labelled cases"'),
    ("Наборы показаны отдельно. В каждом случае проверяются конкретные вопросы к фиксированному состоянию.",
     "The sets are shown separately. Each case checks specific questions against a fixed state."),
    ("<strong>Малые, вручную подобранные наборы.</strong> В stress-наборе — отрицания, непроверенные "
     "советы, посторонние инструкции и устаревшие свидетельства. Эти результаты не оценивают надёжность "
     "на реальном потоке задач.",
     "<strong>Small, hand-picked sets.</strong> The stress set holds negations, untried advice, "
     "unrelated instructions and stale evidence. These results do not measure reliability on a real "
     "stream of work."),
    ('"основной: результаты"', '"primary: results"'),
    ('link(LIVE / "primary-eval/dataset.json", "разметка")', 'link(LIVE / "primary-eval/dataset.json", "labels")'),
    ('"stress: результаты"', '"stress: results"'),
    ('link(LIVE / "challenge-eval/dataset.json", "разметка")', 'link(LIVE / "challenge-eval/dataset.json", "labels")'),
    ("<th>Исходный дефект</th><th>Harness</th><th>Проверок</th><th>Исправлений</th><th>Независимая приёмка</th>",
     "<th>Injected defect</th><th>Harness</th><th>Checks</th><th>Repairs</th><th>Independent acceptance</th>"),
    ("<strong>Почему backend-title-only остановлен.</strong> Jev выбрал %s: P(%s) = %s, но confidence = "
     "<strong>%s</strong> ниже порога <strong>%.2f</strong>. Политика сохранила stop; worker не запускался.",
     "<strong>Why backend-title-only stopped.</strong> Jev picked %s: P(%s) = %s, but confidence = "
     "<strong>%s</strong> is below the threshold <strong>%.2f</strong>. The policy kept the stop and the "
     "worker never ran."),
    ("<div class=\"label\">Отдельное восстановление · selector=%s</div><h2>Тот же backend-дефект, явный "
     "запуск диагностик</h2><div class=\"fine\">%s проверки · %s исправление · %s новых запросов Jev</div>",
     "<div class=\"label\">Separate recovery · selector=%s</div><h2>The same backend defect, diagnostics "
     "run explicitly</h2><div class=\"fine\">%s checks · %s repair · %s new Jev requests</div>"),
    ("<div class=\"fine\">независимая приёмка</div>", "<div class=\"fine\">independent acceptance</div>"),
    ("Восстановление — отдельный опыт после остановки. Оно не превращает первоначальный результат матрицы в %s / %s.",
     "The recovery is a separate experiment run after the stop. It does not turn the original matrix "
     "result into %s / %s."),
    ('"03 / Jev + настоящий Codex", "Успешный ремонт и честная остановка"',
     '"03 / Jev + real Codex", "A successful repair and an honest stop"'),
    ("<strong>%s complete · %s stop · %s ложных complete.</strong> Каждую задачу после остановки проверил "
     "отдельный oracle.",
     "<strong>%s complete · %s stop · %s false completes.</strong> A separate oracle checked every task "
     "afterwards."),
    ('"матрица запусков"', '"run matrix"'),
    ('"Choice при остановке"', '"Choice at the stop"'),
    ('"порог"', '"threshold"'),
    ('link(LIVE / "backend-recovery/recovery.json", "восстановление")',
     'link(LIVE / "backend-recovery/recovery.json", "recovery")'),
    ("<strong>теста прошли</strong><br>Python %s · сохранённый exit code: %s",
     "<strong>tests passed</strong><br>Python %s · saved exit code: %s"),
    ("Команда из метаданных локальной проверки", "Command from the local test metadata"),
    ("Сохранённый вывод unittest · последние 8 строк, без пересказа",
     "Saved unittest output · last 8 lines, verbatim"),
    ("Команда реальной матрицы Jev + Codex из сохранённого журнала",
     "The real Jev + Codex matrix command from the saved log"),
    ("Это просмотр уже сохранённых файлов. Открытие страницы не запускает тесты и не вызывает API.",
     "This is a view of files already saved. Opening the page runs no tests and calls no API."),
    ('"04 / Проверяемость", "Просмотр сохранённого протокола команд"',
     '"04 / Checkability", "A view of the saved command record"'),
    ("Фрагмент настоящего вывода; исходные файлы доступны по ссылкам ниже.",
     "A fragment of the real output. The source files are linked below."),
    ('"полный тестовый лог"', '"full test log"'),
    ('"метаданные тестов"', '"test metadata"'),
    ('"команда матрицы"', '"matrix command"'),
    ('"журнал восстановления"', '"recovery log"'),
    ('<html lang="ru">', '<html lang="en">'),
    ("<title>Jev + Harness · сохранённые протоколы</title>", "<title>Jev + Harness · saved records</title>"),
    ('<div class="dateline">Сохранённые эксперименты · %s</div>',
     '<div class="dateline">Saved experiments · %s</div>'),
    ('<nav aria-label="Виды протокола"><a href="?view=primitives" data-view="primitives">API-ответ</a>'
     '<a href="?view=evaluation" data-view="evaluation">Два набора</a>'
     '<a href="?view=loop" data-view="loop">Цикл ремонта</a>'
     '<a href="?view=tests" data-view="tests">Тесты</a></nav>',
     '<nav aria-label="Record views"><a href="?view=primitives" data-view="primitives">API answer</a>'
     '<a href="?view=evaluation" data-view="evaluation">Two sets</a>'
     '<a href="?view=loop" data-view="loop">Repair loop</a>'
     '<a href="?view=tests" data-view="tests">Tests</a></nav>'),
    ("<span>Собрано из файлов verification/ · секреты и заголовки авторизации не используются</span>",
     "<span>Built from files in verification/ · no secrets and no authorization headers</span>"),
    ('<a href="terminal/evidence-summary.txt">Текстовая сводка</a>',
     '<a href="terminal/evidence-summary.en.txt">Text summary</a>'),
    # text summary
    ('"JEV + HARNESS: ПРОСМОТР СОХРАНЁННОГО ПРОТОКОЛА КОМАНД"',
     '"JEV + HARNESS: A VIEW OF THE SAVED COMMAND RECORD"'),
    ('"Числа ниже вычислены из JSON. Раздел вывода unittest приведён дословно."',
     '"The numbers below are computed from JSON. The unittest output is quoted verbatim."'),
    ('"Открытие галереи или запуск её сборщика не вызывает API и не выполняет тесты."',
     '"Opening the gallery or running its builder calls no API and runs no tests."'),
    ('"Малые подобранные наборы; эти результаты не оценивают надёжность в production."',
     '"Small hand-picked sets. These results do not measure production reliability."'),
    ('"Последние 8 строк terminal/unit-tests-83.txt:"', '"Last 8 lines of terminal/unit-tests-83.txt:"'),
    # outputs
    ('(VERIFICATION / "evidence-gallery.html").write_text(document, encoding="utf-8")',
     '(VERIFICATION / "evidence-gallery.en.html").write_text(document, encoding="utf-8")'),
    ('(VERIFICATION / "terminal/evidence-summary.txt").write_text(summary_text, encoding="utf-8")',
     '(VERIFICATION / "terminal/evidence-summary.en.txt").write_text(summary_text, encoding="utf-8")'),
    ('print("Built verification/evidence-gallery.html and verification/terminal/evidence-summary.txt")',
     'print("Built verification/evidence-gallery.en.html and verification/terminal/evidence-summary.en.txt")'),
]

text = SRC.read_text(encoding="utf-8")
for old, new in PAIRS:
    count = text.count(old)
    if count != 1:
        raise SystemExit("expected exactly one match, found %d for: %s" % (count, old[:70]))
    text = text.replace(old, new, 1)

# The gloss under the ticket needs a style rule; the Russian gallery has no <em> in the ticket.
text = text.replace(
    ".ticket small{display:block;",
    ".ticket em{display:block;font-style:normal;font-size:11px;color:var(--muted);margin-top:7px}"
    ".ticket small{display:block;", 1)

leftover = [ln for ln in text.splitlines() if any("Ѐ" <= ch <= "ӿ" for ch in ln)]
DST.write_text(text, encoding="utf-8")
print("wrote %s" % DST.name)
print("lines that still contain Russian (expected: none):" if not leftover
      else "lines that still contain Russian (%d):" % len(leftover))
for ln in leftover:
    print("  " + ln.strip()[:110])
